name: Bonjour
on:
  - push
jobs:
  add_npm:
    runs-on: ubuntu-22.04
    container: 
      image: ghcr.io/dduportal/esgi-gitpod
      options: --user=root
    steps:
      - name: checkout action
        uses: actions/checkout@v3
      - run: npm install
      - run: npm run lint