name: Bonjour
on:
  - push
jobs:
  add_npm:
    runs-on: ubuntu-22.04
    steps:
      - name: Read README.md
        uses: actions/checkout@v3
      - run: echo "node_modules/" > ./.gitignore
      - run: cat ./.gitignore # Affiche le contenu du fichier `README.md` à la base du dépôt